server:
  port: 8081
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: Dingjd123.+
#    key-store-type: PKCS12
#    key-alias: tomcat

spring:
  appliction:
    name: springbootformac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.demo.entity